apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  version: 0.19.0
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml
  namespace: default
  releaseName: vault
